apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fastchat-controller
  name: fastchat-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastchat-controller
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: fastchat-controller
    spec:
      containers:
        - command:
            - python3
            - -m
            - fastchat.serve.controller
            - --host
            - 0.0.0.0
            - --port
            - "21001"
          image: mandalrajiv/fastchat-intel-extension-pytorch:v1
          name: fastchat-controller
          ports:
            - containerPort: 21001
          resources: {}
      restartPolicy: Always
status: {}
