apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fastchat-model-worker
  name: fastchat-model-worker
spec:
  ports:
    - name: "21002"
      port: 21002
      targetPort: 21002
  selector:
    io.kompose.service: fastchat-model-worker
status:
  loadBalancer: {}
