apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gradio-web-server
  name: gradio-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gradio-web-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gradio-web-server
    spec:
      containers:
        - command:
            - python3
            - -m
            - fastchat.serve.gradio_web_server
            - --controller-url
            - http://fastchat-controller:21001
            - --host
            - 0.0.0.0
            - --share
          image: mandalrajiv/fastchat-intel-extension-pytorch:v1
          name: gradio-web-server
          resources: {}
      restartPolicy: Always
status: {}
