apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gradio-web-server
  name: gradio-service
spec:
  ports:
  - port: 7860
    protocol: TCP
    targetPort: 7860
    nodePort: 30010
  selector:
    io.kompose.service: gradio-web-server
  type: NodePort
status:
  loadBalancer: {}